### ISSUE TITLE
Add a default *file_name_filter* to filter out a list of matching files

### ISSUE THREAD

**Issue by xFrednet** [oli-obk/ui_test#100]
It would be cool to have a simple filter that selects files matching a given set of names. Clippy has used such a filter for a long time and I would also be interested in the same thing for Marker.

Clippy currently uses the following:

```rs
fn test_filter() -> Box<dyn Sync + Fn(&Path) -> bool> {
    if let Ok(filters) = env::var("TESTNAME") {
        let filters: Vec<_> = filters.split(',').map(ToString::to_string).collect();
        Box::new(move |path| filters.iter().any(|f| path.to_string_lossy().contains(f)))
    } else {
        Box::new(|_| true)
    }
}
```
https://github.com/rust-lang/rust-clippy/blob/3be3fb7231677e043317ef026989584ba9a23e37/tests/compile-test.rs#L64-L71

which I believe was implemented by `@oli-obk` . Maybe a simple new function like this would work in the API:

```rs
/// This function will create a filter, that accepts all paths, that contain
/// at least one of the specified keywords. If the filter is empty everything
/// will be accepted
fn create_file_name_filter(keywords: Vec<String>) -> Box<dyn Sync + Fn(&Path) -> bool> {
	if keywords.is_empty() {
		Box::new(|_| true)
	} else {
		Box::new(move |path| keywords.iter().any(|f| path.to_string_lossy().contains(f)))
	}
}
```

I haven't tested this at all, but it should hopefully work. Maybe there is also a better or cleaner method to implement a standard filter like that.

**Comment by oli-obk** [comment]
😅 I just implemented this earlier today. I will actually have a whole CLI parser that will allow `cargo test -- your_filter` to just work like it works for regular `#[test]` tests

**Comment by xFrednet** [comment]
That's awesome! Looking forward to the next release then :D
