### ISSUE TITLE
GitHub actions emitter issues

### ISSUE THREAD

**Issue by Alexendoo** [oli-obk/ui_test#109]
Some things I've spotted about `status_emitter::Gha`:

- [Messages get truncated](https://github.com/rust-lang/rust-clippy/actions/runs/5624871617/job/15242558618#step:7:996), this might be a limitation from GitHub
- [The markdown output isn't rendered](https://github.com/rust-lang/rust-clippy/actions/runs/5624871617), I couldn't see a way to get it to render so this might also be a GitHub limitation
- The error gets printed to the main log multiple times
  1. [From the annotation emission](https://github.com/rust-lang/rust-clippy/actions/runs/5624871617/job/15242558618#step:7:924)
  2. [As the raw? annotation](https://github.com/rust-lang/rust-clippy/actions/runs/5624871617/job/15242558618#step:7:997)
  3. [As the output from `status_emitter::Text`](https://github.com/rust-lang/rust-clippy/actions/runs/5624871617/job/15242558618#step:7:1002)

**Comment by oli-obk** [comment]
Oops the raw annotation is just a debugging "feature" I forgot to remove

**Comment by oli-obk** [comment]
The markdown issue I know of and haven't figured out yet what to do about it. I guess at least for the diffs we could just stop emitting them as GHA messages entirely

**Comment by Alexendoo** [comment]
Can you click annotations to go to where they're emitted in the main log? (I can't find a PR that has annotations) would still be pretty useful without the diff in that case

**Comment by oli-obk** [comment]
I could make the diff annotations appear inline instead of having a big one per file, that should improve some parts. And as a fallback do what you said: just add a message saying a file needs blessing

**Comment by Alexendoo** [comment]
One per hunk would be neat but likely to run into the rather low limit of [10 annotations per step](https://github.com/orgs/community/discussions/26680#discussioncomment-3252835), assuming that thread is still accurate

**Comment by oli-obk** [comment]
> One per hunk would be neat but likely to run into the rather low limit of [10 annotations per step](https://github.com/orgs/community/discussions/26680#discussioncomment-3252835), assuming that thread is still accurate

that's fine. These messages are best effort anyway. As long as you get a few, it becomes helpful enough.

**Comment by RalfJung** [comment]
I'm more worried about them clogging up the logs. Duplicating all messages is going to be very confusing and I'd prefer if we could avoid it, duplicating the diff part is completely unacceptable IMO.

**Comment by oli-obk** [comment]
> duplicating the diff part is completely unacceptable IMO.

it's gone.
