### ISSUE TITLE
Disallow lints in `stderr` that aren't explicitly warn/deny

### ISSUE THREAD

**Issue by Centri3** [oli-obk/ui_test#141]
In clippy, many tests end up inadvertently being tests for other lints as well (for example, `mut_reference` also emitting `needless_pass_by_ref_mut` once). It'd be nice if we could disallow this on the `ui_test` level rather than in CI, somehow.

If this isn't available in the json output (I'm not well versed in that area), we can probably make this an internal lint instead by checking for a `note_once` in the `stderr` without a `warn` attribute anywhere.

**Comment by oli-obk** [comment]
So... detecting `#[deny]` or `#[warn]` attributes and only requiring annotations for those mentioned this way?

**Comment by Centri3** [comment]
More so disallowing them from being emitted at all if there isn't a `#[deny]` or `#[warn]`.

**Comment by oli-obk** [comment]
Hmm... you can add default arguments for all tests (`-Aclippy` may work? If not, just allowing all clippy lint groups may work) and then only the lints you mention with `#[warn]` or `#[deny]` should get emitted.

**Comment by Centri3** [comment]
Yeah that could work and is simpler :+1: Currently `-Aclippy` isn't a thing but maybe we can add that for tests
