### ISSUE TITLE
Support disjunctive filtering in "only"

### ISSUE THREAD

**Issue by RalfJung** [oli-obk/ui_test#162]
It is currently hard to run a test only on x86-64 and x86-32. One might be tempted to try
```
//@only-target-x86_64
//@only-target-i686
```
but that doesn't work since two "only" are interpreted conjunctively: the test only gets run if *all* of them match.

So there are two options:
- we generally treat multiple "only" disjunctively. But then the conjunctive case becomes impossible to express...
- we add new syntax. For instance: `//@only:target-i686|target-x86_64`. We could generally make the syntax `//@only:<filter>` / `//@ignore:<filter>` and keep the old `//@only-<filter>` only for backwards compatibility. (Though honestly `target:x86_64` makes more sense than `target-x86_64`...)

**Comment by oli-obk** [comment]
clippy folk creatively worked around this with

```
//@revisions: i686 x86_64
//@[i686] only-target-i686
//@[x86_64] only-target-x86_64
```
