### ISSUE TITLE
Github summary of test results uses debug representation of test mode

### ISSUE THREAD

**Issue by RalfJung** [oli-obk/ui_test#172]
See for instance https://github.com/rust-lang/miri/actions/runs/6335016176:

> Fail { require_patterns: true, rustfix: Disabled } tests/fail (x86_64-unknown-linux-gnu)

That's not pretty, it should print since more human-readable instead.

**Comment by RalfJung** [comment]
`Mode` has a `Display` impl that is used for the text emitter:
https://github.com/oli-obk/ui_test/blob/c816d896547b58a654e4d9e49cfdeb830aab97ad/src/status_emitter.rs#L417

Maybe it'd make sense to just also use that here?

**Comment by oli-obk** [comment]
`Mode` is gone entirely
