### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by xFrednet** [oli-obk/ui_test#174]
It would be cool if this crate could have a changelog file or something similar that lists all the changes and acts as a migration guide between versions.

Regardless: Thank you for maintaining this crate! :+1:

**Comment by oli-obk** [comment]
Yea... I could have benefitted from that myself 😅

**Comment by oli-obk** [comment]
I'm starting with the changelog from now on and will keep it updated as new changes come in: https://github.com/oli-obk/ui_test/blob/main/CHANGELOG.md
