### ISSUE TITLE
Don't bless `.stderr` and `.stdout` files by default

### ISSUE THREAD

**Issue by xFrednet** [oli-obk/ui_test#176]
The current default behavior of `ui_test::Config::rustc` blesses the `.stdout` and `.stderr` files. I think it would be better to have the default be non blessing, for two reasons:
1. To me, this is an unexpected behavior. Seeing `cargo test` pass, indicated that nothing has changed, while in reality it automatically updated the `.stderr` files
2. The CI can pass, even if files were changed.
    `ui_test` exits with exit code 0, if the `.stderr` and `.stdout` files have been updated. In Marker I had a case, where the CI was marked as green because `ui_test` blessed the files by default and didn't report the mismatch.

I didn't quite know the context of this change, which made blessing the default, but I would recommend changing it back. Both clippy, Marker and I believe rustc support the `RUST_BLESS` environment flag. If a user wants to always auto-bless, they could set that variable globally.

**Comment by oli-obk** [comment]
Yea ^^ I prefer blessing by default and thus switched it. We could change it to be based off `RUST_BLESS` as well as the command line flag

**Comment by xFrednet** [comment]
Sometimes I also bless directly. But out of interest, how do you use `ui_test` in a CI then? Do you check with git that there no been any updated files?

**Comment by oli-obk** [comment]
I run it with `--check` 😆 I know that's a bit fragile. I was considering requiring either `--bless` or `--check` (and erroring if neither is passed) and thus avoiding any ambiguity about the defaults this way. But I guess I can resolve this just by going back to check mode by default. I just got fed up of `cargo test -- -- --bless` being my default command ^^

**Comment by xFrednet** [comment]
Ahhh, I didn't even know about the `--check` flag. :sweat_smile: The main README mentions it once, but doesn't explain what it does.

I would favor the environment value one solution, then every user can set that environment value on their machine, if they want to bless by default.

**Comment by oli-obk** [comment]
> I would favor the environment value one solution, then every user can set that environment value on their machine, if they want to bless by default.

Oh now I remember why I actually changed it. Windows users can't really work with env vars nicely :D and I was debugging a windows issue. But I think with today's setup, I can make it so everyone can have their favorite workflow by default.

**Comment by RalfJung** [comment]
I also ran into this -- I would expect tests by default to actually test something, i.e., bless=false and check=true. It took me a bit to figure out why my test suite wasn't actually testing the output. This could have easily slipped into the repository and then CI would have silently accepted changes that break the tests!

Having bless on-by-default or check off-by-default is a really dangerous default.
