### ISSUE TITLE
Remove rust-toolchain.toml?

### ISSUE THREAD

**Issue by RalfJung** [oli-obk/ui_test#18]
ui_test just installed Rust 1.63.0 on my system, due to its `rust-toolchain.toml`. I don't think I want it to do that -- I am typically sticking to stable and nightly and would rather not have one toolchain installed for each crate.

Can we change that to say `stable`, or remove the file altogether?

**Comment by RalfJung** [comment]
Furthermore the `profile = "minimal"` in that file leads to issues; it means that rust-analyzer cannot find the stdlib source code.

**Comment by oli-obk** [comment]
Yea seems fine, I don't remember why I made it this strict

**Comment by RalfJung** [comment]
Which of these various options seems fine? Removing the file entirely? :D

Judging from some of the commit messages it seems like this was mostly meant for CI, but CI settings should really be in the CI yml file and not in rust-toolchain.toml.

**Comment by oli-obk** [comment]
> Removing the file entirely? :D

Yea, was answering the issue title ^^
