### ISSUE TITLE
Applying suggestions from different files

### ISSUE THREAD

**Issue by y21** [oli-obk/ui_test#191]
In rust-lang/rust-clippy#12180 I'm trying to add a suggestion to an error in the clippy.toml (specifically when an invalid field is found and there is one that is very similar, e.g. accidentally using underscores instead of dashes).

There's a ui test for the [clippy.toml file already](https://github.com/rust-lang/rust-clippy/blob/master/tests/ui-toml/toml_unknown_key/conf_unknown_key.rs), but up to this point it didn't have to deal with suggestions and rustfix, but now that it emits a suggestion, there's an issue with it, which is that it tries to pass the .rs file to rustfix even though the suggestion is in the clippy.toml file, which results in an error like `"Invalid range 133...165 given, original data is only 78 byte long"`.

Quickly skimming over the code (correct me if I'm wrong), it seems like uitest always passes the path of the .rs file to be tested, regardless of where the diagnostic/suggestion *actually* comes from? Is this a bug, or is it expected and there's some way around it?

https://github.com/oli-obk/ui_test/blob/6b567fdb2efed6c967e5b739b20a751a1968a935/src/lib.rs#L878

`path` here is always the input file path

**Comment by oli-obk** [comment]
good catch. That seems very fixable 😆

**Comment by y21** [comment]
> You can disable rustfix with `//@no-rustfix` for that specific test

yep that's what I did but wasn't sure if there's a better way, so I thought I would just ask here. But if there isn't, that's fine too. Thanks!
