### ISSUE TITLE
Dependency resolution panics when specifying path dependecy without version field.

### ISSUE THREAD

**Issue by Brezak** [oli-obk/ui_test#211]
When using `Config::cargo` omitting the version field in a path dependency will cause the testing framework to panic with a `dependency does not exist` message.
The bug happens in this piece of code:
https://github.com/oli-obk/ui_test/blob/680bb08472477c0cb463b76c5fdf5bb22fff3b31/src/dependencies.rs#L164-L183
Specifically line 177. Our buggy dependency will have it's `req` field contain no version requirement comparators so the `matches` call will never return true. Causing the predicate to always returns false.

**Comment by oli-obk** [comment]
Oh heh, good catch. Should be easy to fix

**Comment by oli-obk** [comment]
I am unable to reproduce this. Do you have more info on your setup?

**Comment by Brezak** [comment]
My setup is this branch in my fork of bevy https://github.com/Brezak/bevy/tree/ui-test. The tests are 3 crates excluded from the bevy workspace. Namely `bevy_ecs_compile_fail_tests`, `bevy_macros_compile_fail_tests` and `bevy_reflect_compile_fail_tests`. They all import the crates they're testing as path dependencies. If the version field for their test crate dependency is missing all their tests start failing with the message `dependency does not exist`.

I've been trying to create a smaller reproduction. I'll report back if I succeed.

**Comment by oli-obk** [comment]
ooh, that's funky, thanks!
