### ISSUE TITLE
Default output_conflict_handling ignores test failures

### ISSUE THREAD

**Issue by RalfJung** [oli-obk/ui_test#227]
This seems like a bad default:

https://github.com/oli-obk/ui_test/blob/266e25dc6def7f323178d58c06048934a7b08210/src/config.rs#L141

**Comment by RalfJung** [comment]
In fact it's even worse... I have set `output_conflict_handling` to `Error`, but `run_tests` by default overwrites it back to `Bless`!

**Comment by oli-obk** [comment]
The first part is https://github.com/oli-obk/ui_test/issues/176

The second part should only happen if `--bless` is passed as an argument. I did a quick skim of the code and I don't see how else the behaviour you're describing could happen

**Comment by RalfJung** [comment]
This may have changed in master.  In 0.21.1 we have

https://github.com/oli-obk/ui_test/blob/3d262a2be8cd2024c5108fa02d6f8047c4d61a75/src/lib.rs#L129

where the `true` sets `default_bless`.

**Comment by RalfJung** [comment]
However even in the last commit, something seems odd here -- `args.check` seems to be off-by-default?

Maybe there should be a test using `run_tests` with an all-default configuration and just making sure that this actually complains about output differences.

**Comment by oli-obk** [comment]
> -- `args.check` seems to be off-by-default?

That's irrelevant, if it isn't set the default isn't changed.

**Comment by oli-obk** [comment]
> A different default would make `--check` redundant though, it should be `--no-check` then

you can still change the default in your Config and then parse the command line flags
