### ISSUE TITLE
Allow different comment than `//`

### ISSUE THREAD

**Issue by hellow554** [oli-obk/ui_test#239]
I would like to use `ui_test` for an assembler written in rust where `;` is used to start comments.

There are only a few places in https://github.com/oli-obk/ui_test/blob/main/src/parser.rs which needs to be adjustet.

Since there's already a [`custom_comments`](https://docs.rs/ui_test/latest/ui_test/struct.Config.html#structfield.custom_comments) field, wouldn't it be possible to either adjust that field to parse the `//@` respectively `;@` beginning or introduce a new field on config named `comment_prefix` or similar.

What do you think?

**Comment by oli-obk** [comment]
Yea I want to support this, but am not sure yet how to best make it configurable. We'll probably need to try out a few schemes and see what is best
