### ISSUE TITLE
implement //@only-x86_64 and similar filters

### ISSUE THREAD

**Issue by oli-obk** [oli-obk/ui_test#24]
also improve the errors around wrong comments

**Comment by RalfJung** [comment]
We have `only-target-x64_64`, what is the advantage of also having `only-x86_64`?

**Comment by oli-obk** [comment]
We don't afaict. At least we tried it and it just didn't parse at all

**Comment by RalfJung** [comment]
We probably need to add digits and underscores here:

https://github.com/oli-obk/ui_test/blob/4f612b4bd8ead1eb061495822a81e20d78d8949e/src/parser.rs#L128-L131

**Comment by oli-obk** [comment]
Probably ^^ still should improve the diagnostic to help people figure out what the heck is going on
