### ISSUE TITLE
Option to disable GitHub job summary

### ISSUE THREAD

**Issue by daxpedda** [oli-obk/ui_test#258]
I'm starting to use job summaries lately and the output generated by `ui_test` creates some noise at this point.
Looking through the source code I couldn't find a way to disable GitHub job summaries.

Would a PR adding, lets say an environment variable to disable it, be alright?

**Comment by oli-obk** [comment]
You can't disable it, but you can "not use it" instead. You need to use `run_tests_generic` and only use the `Text` status emitter. `run_tests` by default uses a tuple of `Text` and `Gha`

**Comment by daxpedda** [comment]
Thanks, that worked fine for me!
