### ISSUE TITLE
Number of tests differs from progress bar max

### ISSUE THREAD

**Issue by oli-obk** [oli-obk/ui_test#261]
We avoid counting revisions towards the progress bar maximum, but we count them as tests that passed/failed. Unsure how to best handle this, as there was some preference (by @RalfJung I think?) that the progress bar show the number of actual test files and not count revisions (thus now grow in length as the tests are being parsed). But changing the final count is also annoying, as we'd have to group tests together before printing the final information. Unsure what is best here.

Looks like this:

![grafik](https://github.com/user-attachments/assets/dc66819d-10c4-4627-9557-093544094a12)

**Comment by RalfJung** [comment]
>  there was some preference (by @RalfJung I think?) that the progress bar show the number of actual test files and not count revisions (thus now grow in length as the tests are being parsed)

(I assume this should say "not grow in length".)

I do find the change in length initially confusing, but it makes sense, so I don't mind that behavior.
