### ISSUE TITLE
clippy test shows: assertion failed: progress.is_finished()

### ISSUE THREAD

**Issue by RalfJung** [oli-obk/ui_test#264]
This seems fairly reproducible: when I run clippy tests in the rustc repo via `./x.py test clippy --stage 2`, the output includes this:
```
thread '<unnamed>' panicked at /home/r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ui_test-0.25.0/src/status_emitter.rs:252:17:
assertion failed: progress.is_finished()
```
However, the tests are still considered to "pass".

**Comment by oli-obk** [comment]
How did that ever land?

**Comment by oli-obk** [comment]
Ah CI doesn't have a progress bar and thus doesn't have the assert. This only happens in --quiet mode, too, which is the default in rust-lang/rust. This is already fixed on main
