### ISSUE TITLE
Add support for revisions without rustc

### ISSUE THREAD

**Issue by DaniPopes** [oli-obk/ui_test#290]
Currently specifying the directive `@revisions <revision>...` implicitly appends `--cfg=<revision> -Cextra-filename=<revision>` to the compile flags, assuming the command is a rustc driver.

It would be nice to be able to use this without a rustc driver for running a test multiple times with different configurations and different output files.

I was thinking to add a simple config flag that turns the implicit compile flags off, since AFAICT this is the only implicit behavior of the directive. If this is acceptable I can open a PR to implement this.

**Comment by oli-obk** [comment]
Hmm... revisions are pretty special, but maybe we can still make them a `Flag`.

If we can't, we make the "command line flag adding" a `Flag` that you can either not set at all, or create your own version of if you want it to set env vars or different flags instead. The `apply` function can query the revision from the status emitter
