### ISSUE TITLE
Option 'crate-name' given more than once

### ISSUE THREAD

**Issue by smoelius** [oli-obk/ui_test#293]
I think the logic here may not account for `--crate-name` already appearing in `cmd`: https://github.com/oli-obk/ui_test/blob/a2a7d13b0394767f5770eb563fc7fc30a3b780e5/src/custom_flags/rustfix.rs#L215-L216
I am running some tests on Clippy, and I am seeing a command like the following (slightly reformatted):
```
command:
CLIPPY_CONF_DIR="tests/ui-toml/toml_disallowed_methods"
RUSTC_ICE="0"
"clippy-driver"
"--error-format=json"
"--emit=metadata"
"-Aunused"
"-Ainternal_features"
"-Zui-testing"
"-Zdeduplicate-diagnostics=no"
"-Dwarnings"

...

"--out-dir"
"target/ui_test/tests/ui-toml/toml_disallowed_methods"
"tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.fixed"
"--crate-name"                                                        # <---
"conf_disallowed_methods"
"--edition"
"2021"
"--crate-name"                                                        # <---
"__conf_disallowed_methods_1"
```

**Comment by smoelius** [comment]
I just noticed this, implying the fault is not `ui_test`'s:
https://github.com/rust-lang/rust-clippy/blob/f712eb5cdccd121d0569af12f20e6a0fabe4364d/tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.rs#L1

Sorry for the noise.

**Comment by oli-obk** [comment]
Why does that test do that? We could make ui_test support setting the crate name if that's useful

**Comment by smoelius** [comment]
Thanks for following up. I _think_ it's to make names resolve properly: https://github.com/rust-lang/rust-clippy/blob/f712eb5cdccd121d0569af12f20e6a0fabe4364d/tests/ui-toml/toml_disallowed_methods/clippy.toml#L12-L16

Either way, I have a workaround, and there's no bug in `ui_test`. So I think there's nothing to do here.

Thanks again.
