### ISSUE TITLE
Support revisions on global commands

### ISSUE THREAD

**Issue by RalfJung** [oli-obk/ui_test#31]
From what I could tell, revisions are currently only supported on error patterns. Would be nice to also support them on global commands, so that one can do things like
```
//@revisions: isolated free
//@only-target-linux
//[free]@compile-flags: -Zmiri-disable-isolation
```

FWIW I would have probably picked this syntax
```
//@revisions: isolated free
//@only-target-linux
//@[free]compile-flags: -Zmiri-disable-isolation
```
but that would be inconsistent with `//[fn_ptr]~^ ERROR: pattern`... maybe we should change that to `//~[fn_ptr]^ ERROR: pattern`, too, so that the first character after the `//` always indicates what this is?

OTOH, that might create parsing ambiguities if there is no ERROR level, and `//[revision]` is also consistent, so... whatever.

**Comment by oli-obk** [comment]
We could require `//@[revision]~ foo` if you want to use revisions

**Comment by RalfJung** [comment]
That feels odd, I associate `@` with global commands and `~` with patterns.

**Comment by oli-obk** [comment]
considering square brackets in diagnostics are rare and you could always use a longer or regex pattern in that case (and get an error if that `[revision]` is not actually a revision), I think we should just use the possibly ambigous case

**Comment by RalfJung** [comment]
I forgot, do we even still have the no-error-level syntax?

**Comment by oli-obk** [comment]
oh haha, no I scrapped that and added a global min-level flag to get the "don't require annotaitons for all notes" behaviour. Ok no ambiguity, woo

**Comment by RalfJung** [comment]
Right so the only question is if we want to incur all that churn for when/if rustc itself uses this crate.

**Comment by oli-obk** [comment]
> Right so the only question is if we want to incur all that churn for when/if rustc itself uses this crate.

I can incrementally move the rustc test suite to use the same syntax to keep the final diff small
