### ISSUE TITLE
Testing with clippy?

### ISSUE THREAD

**Issue by peter-kehl** [oli-obk/ui_test#57]
Not a mainstream use case: To test that some code fails `cargo clippy`. (OK to restrict/specialize for Github Actions, and locally on Linux/Mac OS.) Any feasible way, please?

(The actual use case: Internal tests of a crate generating attribute macros that inject `#[allow(clippy::xyz...)]`.)

(This issue/question is parallel to https://github.com/dtolnay/trybuild/issues/235.)

**Comment by oli-obk** [comment]
do you mean `cargo clippy` or just `clippy-driver` directly?

For the former: you can have a look how [ui_test tests itself](https://github.com/oli-obk/ui_test/blob/424c5cb6c196cbcd4736719edc20b6e8aaf55478/tests/integration.rs#L22). That uses `cargo test`, but you can trivially adjust that to be using `cargo clippy`. This self-test suite isn't very trivial to set up, so I'd be happy to make this all a bit easier by providing a `Config` method builder other than `Config::default()` that immediately sets up everything correctly.

For the latter: You should be able to do that by setting `config.program.program` to `clippy-driver`. You may have to specify the entire path to the `clippy-driver` on your system, but that may be achievable by asking rustc where it is and replacing the final part of that path with `clippy-driver`.

**Comment by peter-kehl** [comment]
Thank you. I'm looking at `tests/integrations` and `tests/integration.rs`. Quite complex (combining too many features).

Are there any examples, or crates, that use `ui_test` in simpler/pointed ways? Or any  documentation (other than rustdoc)?

**Comment by peter-kehl** [comment]
I've copied & simplified `integration.rs` into https://github.com/coop-rs/allows/blob/main/allows/tests/internal_checks/main.rs#L74. (For now, `cargo test` is enough, `cargo clippy` for later.) But, I don't understand "$DIR" at all, and `RUST_BACKTRACE=1 cargo test` fails if I leave that line number 74 there:
```
Running tests/internal_checks/main.rs (target/debug/deps/internal_checks-1d37d736e19ac148)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/pkehl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ui_test-0.8.2/src/lib.rs:125:43
stack backtrace:
0: rust_begin_unwind
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/result.rs:1076:23
   4: ui_test::Config::path_stderr_filter
             at /home/pkehl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ui_test-0.8.2/src/lib.rs:125:23
   5: internal_checks::run
             at ./tests/internal_checks/main.rs:77:5
   6: internal_checks::main
             at ./tests/internal_checks/main.rs:8:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/ops/function.rs:250:5
```

It has one crate to test, and it should fail: https://github.com/coop-rs/allows/blob/main/allows/tests/internal_checks/incorrect_lint/Cargo.toml. But, running `cargo test` in the root (of the GIT clone of https://github.com/coop-rs/allows) doesn't check that inner crate:
```
Running tests/internal_checks/main.rs (target/debug/deps/internal_checks-1d37d736e19ac148)

test result: ok. 0 tests passed, 0 ignored, 0 filtered out
```

Any light, please?

**Comment by oli-obk** [comment]
It looks like you ended up setting it up correctly?

At least I am seeing

```
> cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.05s
     Running unittests src/lib.rs (target/debug/deps/allow_tests-eec7e140187d4884)

running 1 test
test test_unused ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/internal_checks/main.rs (target/debug/deps/internal_checks-6115f707ed3f45ca)
tests/internal_checks/incorrect_lint/Cargo.toml ... FAILED

tests/internal_checks/incorrect_lint/Cargo.toml FAILED:
command: BLESS="false" "cargo" "test" "--color" "never" "--quiet" "--jobs" "1" "--no-fail-fast" "--target-dir" "tests/target" "--manifest-path" "tests/internal_checks/incorrect_lint/Cargo.toml"

fail test got exit status: 0, but expected 1

actual output differed from expected
--- tests/internal_checks/incorrect_lint/Cargo.stderr
+++ <stderr output>
+warning: unused macro definition: `standard_lint_versioned`
+  --> src/wrapper_macros.rs:19:14
+   |
+19 | macro_rules! standard_lint_versioned {
+   |              ^^^^^^^^^^^^^^^^^^^^^^^
+   |
+   = note: `#[warn(unused_macros)]` on by default
+
+warning: unused macro definition: `standard_lint_nightly`
+  --> src/wrapper_macros.rs:28:14
+   |
+28 | macro_rules! standard_lint_nightly {
+   |              ^^^^^^^^^^^^^^^^^^^^^
+
+warning: unused macro definition: `prefixed_lint_versioned`
+  --> src/wrapper_macros.rs:35:14
+   |
+35 | macro_rules! prefixed_lint_versioned {
+   |              ^^^^^^^^^^^^^^^^^^^^^^^
+
+


actual output differed from expected
--- tests/internal_checks/incorrect_lint/Cargo.stdout
+++ <stderr output>
+
+running 0 tests
+
+test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished 
+
+
+running 0 tests
+
+test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished 
+
+
```

You'll still need a way to change `output_conflict_handling` to `Bless` to generate the ui files.

I'll create a `Config` method for constructing a config file for `cargo` subcommands.
